# Generated by Django 6.0.1 on 2026-01-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Escola",
            fields=[
                ("id_escola", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("codigo_inep", models.CharField(max_length=10)),
                ("tipo_escola", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("num_alunos", models.IntegerField()),
            ],
            options={
                "db_table": "escolas",
            },
        ),
    ]
